from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-recovery/', views.password_recovery, name='password_recovery'),
    path('password-recovery/verify/', views.password_recovery_verify, name='password_recovery_verify'),
    path('password-recovery/reset/', views.password_recovery_reset, name='password_recovery_reset'),
    path('profile/', views.profile, name='profile'),
    path('2fa/setup/', views.TwoFactorSetupView.as_view(), name='two_factor_setup'),
    path('users/', views.user_list, name='user_list'),
    path('user_list/', views.redirect_to_users, name='user_list_old'),
    path('users/ajouter/', views.user_create, name='user_create'),
    path('users/<int:pk>/', views.user_edit, name='user_edit'),
    path('users/<int:pk>/supprimer/', views.user_delete, name='user_delete'),
    path('users/<int:pk>/toggle/', views.user_toggle_active, name='user_toggle_active'),
    path('users/<int:pk>/approuver/', views.user_approve, name='user_approve'),
    path('users/<int:pk>/password/', views.user_show_password, name='user_show_password'),
    path('users/<int:pk>/password/reset/', views.user_reset_password, name='user_reset_password'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:pk>/', views.notification_detail, name='notification_detail'),
    path('notifications/marquer-tout/', views.notification_mark_all_read, name='notification_mark_all_read'),
    path('messages/', views.message_list, name='message_list'),
    path('messages/nouveau/', views.message_create, name='message_create'),
    path('messages/<int:pk>/', views.message_detail, name='message_detail'),
    path('messages/marquer-tout/', views.message_mark_all_read, name='message_mark_all_read'),
    path('chat/', views.chat_inbox, name='chat_inbox'),
    path('chat/nouveau/', views.chat_new, name='chat_new'),
    path('chat/.select-user/', views.chat_new, name='chat_select_user'),
    path('chat/<int:user_id>/', views.chat_conversation, name='chat_conversation'),
    path('demandes/', views.demande_list, name='demande_list'),
    path('demandes/<int:pk>/', views.demande_detail, name='demande_detail'),
    path('demandes/<int:pk>/approuver/', views.demande_approuver, name='demande_approuver'),
    path('demandes/<int:pk>/rejeter/', views.demande_rejeter, name='demande_rejeter'),
    path('comptes-bloques/', views.locked_accounts, name='locked_accounts'),
    path('comptes-bloques/<str:username>/deverrouiller/', views.unlock_account, name='unlock_account'),
    path('permissions-modifications/', views.permission_modification_list, name='permission_modification_list'),
    path('permissions-modifications/<int:pk>/', views.permission_modification_detail, name='permission_modification_detail'),
    path('permissions-modifications/<int:pk>/approuver/', views.permission_modification_approuver, name='permission_modification_approuver'),
    path('permissions-modifications/<int:pk>/rejeter/', views.permission_modification_rejeter, name='permission_modification_rejeter'),
    path('permissions-utilisateur/', views.permission_utilisateur_list, name='permission_utilisateur_list'),
    path('permissions-utilisateur/ajouter/', views.permission_utilisateur_create, name='permission_utilisateur_create'),
    path('permissions-utilisateur/<int:pk>/modifier/', views.permission_utilisateur_edit, name='permission_utilisateur_edit'),
    path('permissions-utilisateur/<int:pk>/supprimer/', views.permission_utilisateur_delete, name='permission_utilisateur_delete'),
    path('utilisateur/<int:user_id>/permissions/', views.user_permissions_detail, name='user_permissions_detail'),
    path('utilisateur/<int:user_id>/permissions/<str:module_code>/', views.user_permission_toggle, name='user_permission_toggle'),
]
