# Generated by Django 5.2.13 on 2026-04-18 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('enseignement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.TextField()),
                ('telephone_parent', models.CharField(blank=True, max_length=20)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scolarite/photos/')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('ancien', 'Ancien'), ('suspendu', 'Suspendu'), ('radié', 'Radié')], default='actif', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveauscolaire', verbose_name='Niveau de classe')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('traitements_en_cours', models.TextField(blank=True, verbose_name='Traitements en cours')),
                ('vaccinations', models.TextField(blank=True, verbose_name='Vaccinations')),
                ('allergies_medicamenteuses', models.TextField(blank=True, verbose_name='Allergies médicamenteuses')),
                ('maladies_chroniques', models.TextField(blank=True, verbose_name='Maladies chroniques')),
                ('contacts_urgence_nom', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence (nom)")),
                ('contacts_urgence_tel', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence (téléphone)")),
                ('contacts_urgence_lien', models.CharField(blank=True, max_length=50, verbose_name="Lien avec l'élève")),
                ('medecin_traitant', models.CharField(blank=True, max_length=100, verbose_name='Médecin traitant')),
                ('tel_medecin', models.CharField(blank=True, max_length=20, verbose_name='Téléphone médecin')),
                ('observations', models.TextField(blank=True)),
                ('date_derniere_mise_a_jour', models.DateField(auto_now=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
            },
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('acte_naissance', 'Acte de naissance'), ('certificat_scolarite', 'Certificat de scolarité'), ('certificat_medical', 'Certificat médical'), ('photo_identite', "Photo d'identité"), ('bulletin_precedent', 'Bulletin précédent'), ('autre', 'Autre')], max_length=30)),
                ('fichier', models.FileField(upload_to='scolarite/documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Document Élève',
                'verbose_name_plural': 'Documents Élèves',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='EleveInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('rang', models.PositiveIntegerField(default=0)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien'), ('excellent', 'Excellent')], max_length=20)),
                ('decision', models.CharField(blank=True, max_length=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='core.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='enseignement.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-annee_scolaire__date_debut', 'rang'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='ParentTuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien_parente', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='N° WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('est_contact_principal', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Parent/Tuteur',
                'verbose_name_plural': 'Parents/Tuteurs',
                'ordering': ['-est_contact_principal', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SanctionRecompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sanction', 'Sanction'), ('recompense', 'Récompense')], max_length=20)),
                ('type_detail', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_incident', models.DateField()),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('est_signale', models.BooleanField(default=False, verbose_name='Signalé aux parents')),
                ('statut_traitement', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=20)),
                ('points', models.IntegerField(default=0, help_text='Points à déduire ou ajouter (- pour sanction, + pour récompense)')),
                ('service_traitant', models.CharField(blank=True, choices=[('surveillance', 'Surveillance et Contrôle'), ('direction', 'Direction Générale'), ('admin', 'Administrateur')], max_length=20)),
                ('date_traitement', models.DateField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='scolarite.eleve')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='scolarite.eleveinscription')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodeevaluation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanction/Récompense',
                'verbose_name_plural': 'Sanctions/Récompenses',
                'ordering': ['-date_incident'],
            },
        ),
        migrations.CreateModel(
            name='ClotureNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_clotures', to='enseignement.classe')),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_clotures', to='core.periodeevaluation')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_clotures', to='enseignement.profilprofesseur')),
            ],
            options={
                'verbose_name': 'Clôture de notes',
                'verbose_name_plural': 'Clôtures de notes',
                'unique_together': {('classe', 'professeur', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='CloturePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures', to='enseignement.classe')),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures', to='core.periodeevaluation')),
            ],
            options={
                'verbose_name': 'Clôture de période',
                'verbose_name_plural': 'Clôtures de périodes',
                'unique_together': {('classe', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationConduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_base', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduite_configs', to='core.anneescolaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduite_configs', to='core.niveauscolaire')),
            ],
            options={
                'verbose_name': 'Configuration Conduite',
                'verbose_name_plural': 'Configurations Conduite',
                'ordering': ['annee_scolaire', 'niveau'],
                'unique_together': {('annee_scolaire', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='ConduiteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_base', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_recompenses', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note_finale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_maj', models.DateField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduites', to='scolarite.eleveinscription')),
            ],
            options={
                'verbose_name': 'Conduite Élève',
                'verbose_name_plural': 'Conduites Élèves',
                'unique_together': {('inscription',)},
            },
        ),
    ]
