# Generated by Django 5.2 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
        ('core', '0001_initial'),
        ('enseignement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureAnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('est_validee', models.BooleanField(default=False, verbose_name='Clôture validée')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures_annee', to='enseignement.classe')),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clôture Année Scolaire',
                'verbose_name_plural': 'Clôtures Année Scolaire',
                'unique_together': {('classe', 'annee_scolaire')},
            },
        ),
    ]