# Generated by Django 6.0.3 on 2026-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.TextField()),
                ('telephone_parent', models.CharField(blank=True, max_length=20)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('ancien', 'Ancien'), ('suspendu', 'Suspendu'), ('radié', 'Radié')], default='actif', max_length=20)),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('rang', models.PositiveIntegerField(default=0)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien'), ('excellent', 'Excellent')], max_length=20)),
                ('decision', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-annee_scolaire__date_debut', 'rang'],
            },
        ),
    ]
