# Generated by Django 5.2.3 on 2026-04-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sanction', 'Sanction'), ('recompense', 'Récompense')], max_length=20)),
                ('type_detail', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_incident', models.DateField()),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('est_signale', models.BooleanField(default=False, verbose_name='Signelé aux parents')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='eleves.eleve')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='eleves.inscription')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ['-date_incident'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('acte_naissance', 'Acte de naissance'), ('certificat_scolarite', 'Certificat de scolarité'), ('certificat_medical', 'Certificat médical'), ('photo_identite', "Photo d'identité"), ('bulletin_precedent', 'Bulletin précédent'), ('autre', 'Autre')], max_length=30)),
                ('fichier', models.FileField(upload_to='eleves/documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Document Élève',
                'verbose_name_plural': 'Documents Élèves',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('traitements_en_cours', models.TextField(blank=True, verbose_name='Traitements en cours')),
                ('vaccinations', models.TextField(blank=True, verbose_name='Vaccinations')),
                ('allergies_medicamenteuses', models.TextField(blank=True, verbose_name='Allergies médicamenteuses')),
                ('maladies_chroniques', models.TextField(blank=True, verbose_name='Maladies chroniques')),
                ('contacts_urgence_nom', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence (nom)")),
                ('contacts_urgence_tel', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence (téléphone)")),
                ('contacts_urgence_lien', models.CharField(blank=True, max_length=50, verbose_name="Lien avec l'élève")),
                ('medecin_traitant', models.CharField(blank=True, max_length=100, verbose_name='Médecin traitant')),
                ('tel_medecin', models.CharField(blank=True, max_length=20, verbose_name='Téléphone médecin')),
                ('observations', models.TextField(blank=True)),
                ('date_derniere_mise_a_jour', models.DateField(auto_now=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
            },
        ),
        migrations.CreateModel(
            name='ParentTuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien_parente', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='N° WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('est_contact_principal', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Parent/Tuteur',
                'verbose_name_plural': 'Parents/Tuteurs',
                'ordering': ['-est_contact_principal', 'nom'],
            },
        ),
    ]
