# Generated by Django 5.2.3 on 2026-04-06 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_add_new_modules'),
        ('finances', '0010_add_new_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineeleve',
            name='date_traitement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineeleve',
            name='points',
            field=models.IntegerField(default=0, help_text='Points à déduire ou ajouter (- pour sanction, + pour récompense)'),
        ),
        migrations.AddField(
            model_name='disciplineeleve',
            name='service_traitant',
            field=models.CharField(blank=True, choices=[('surveillance', 'Surveillance et Contrôle'), ('direction', 'Direction Générale'), ('admin', 'Administrateur')], max_length=20),
        ),
        migrations.AddField(
            model_name='disciplineeleve',
            name='statut_traitement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplineeleve',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplineeleve',
            name='est_signale',
            field=models.BooleanField(default=False, verbose_name='Signalé aux parents'),
        ),
        migrations.CreateModel(
            name='ConduiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('Maternelle1', 'Maternelle 1'), ('Maternelle2', 'Maternelle 2'), ('CP1', 'Cours Préparatoire 1'), ('CP2', 'Cours Préparatoire 2'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('6e', 'Sixième'), ('5e', 'Cinquième'), ('4e', 'Quatrième'), ('3e', 'Troisième'), ('2nde', 'Seconde'), ('1re', 'Première'), ('Tle', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=20)),
                ('periode', models.PositiveIntegerField(help_text='1 = Trim/Semestre 1, 2 = Trim/Semestre 2, etc.')),
                ('note_base', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduite_configs', to='finances.anneescolaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Conduite',
                'verbose_name_plural': 'Configurations Conduite',
                'ordering': ['annee_scolaire', 'periode', 'niveau'],
                'unique_together': {('annee_scolaire', 'niveau', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='ConduiteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.PositiveIntegerField(help_text='1 = Trim/Semestre 1, 2 = Trim/Semestre 2, etc.')),
                ('note_base', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_recompenses', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note_finale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_maj', models.DateField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduites', to='eleves.inscription')),
            ],
            options={
                'verbose_name': 'Conduite Élève',
                'verbose_name_plural': 'Conduites Élèves',
                'ordering': ['periode'],
                'unique_together': {('inscription', 'periode')},
            },
        ),
    ]
