# Generated by Django 5.2.3 on 2026-04-06 15:04

from django.db import migrations


def consolidate_conduite_records(apps, schema_editor):
    ConduiteEleve = apps.get_model('eleves', 'ConduiteEleve')
    ConduiteConfig = apps.get_model('eleves', 'ConduiteConfig')
    
    # Pour ConduiteEleve: conserver un seul enregistrement par inscription
    inscriptions = ConduiteEleve.objects.values_list('inscription_id', flat=True).distinct()
    for inscription_id in inscriptions:
        records = list(ConduiteEleve.objects.filter(inscription_id=inscription_id).order_by('-note_finale'))
        if len(records) > 1:
            first = records[0]
            total_ded = sum(r.total_deductions for r in records)
            total_rec = sum(r.total_recompenses for r in records)
            
            first.total_deductions = total_ded
            first.total_recompenses = total_rec
            first.note_finale = first.note_base - total_ded + total_rec
            if first.note_finale > 20:
                first.note_finale = 20
            if first.note_finale < -20:
                first.note_finale = -20
            first.save()
            
            # Supprimer les autres
            ConduiteEleve.objects.filter(inscription_id=inscription_id).exclude(pk=first.pk).delete()
    
    # Pour ConduiteConfig: garder une seule config par niveau (la première)
    annee_ids = ConduiteConfig.objects.values_list('annee_scolaire_id', flat=True).distinct()
    for annee_id in annee_ids:
        niveaux = ConduiteConfig.objects.filter(annee_scolaire_id=annee_id).values_list('niveau', flat=True).distinct()
        for niveau in niveaux:
            records = list(ConduiteConfig.objects.filter(annee_scolaire_id=annee_id, niveau=niveau).order_by('id'))
            if len(records) > 1:
                ConduiteConfig.objects.filter(annee_scolaire_id=annee_id, niveau=niveau).exclude(pk=records[0].pk).delete()


def reverse_consolidation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_add_discipline_enhanced'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.RunPython(consolidate_conduite_records, reverse_consolidation),
        migrations.AlterModelOptions(
            name='conduiteconfig',
            options={'ordering': ['annee_scolaire', 'niveau'], 'verbose_name': 'Configuration Conduite', 'verbose_name_plural': 'Configurations Conduite'},
        ),
        migrations.AlterModelOptions(
            name='conduiteeleve',
            options={'verbose_name': 'Conduite Élève', 'verbose_name_plural': 'Conduites Élèves'},
        ),
        migrations.AlterUniqueTogether(
            name='conduiteconfig',
            unique_together={('annee_scolaire', 'niveau')},
        ),
        migrations.AlterUniqueTogether(
            name='conduiteeleve',
            unique_together={('inscription',)},
        ),
        migrations.RemoveField(
            model_name='conduiteconfig',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='conduiteeleve',
            name='periode',
        ),
    ]