# Generated by Django 5.2.3 on 2026-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0005_conduite_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineeleve',
            name='periode',
            field=models.PositiveIntegerField(blank=True, help_text='1 = Trim/Semestre 1, 2 = Trim/Semestre 2, 3 = Trim/Semestre 3', null=True),
        ),
    ]
