# Generated by Django 5.2.3 on 2026-04-06 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_classe_options_alter_classe_unique_together_and_more'),
        ('eleves', '0007_add_periode_cloture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePeriodeCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.PositiveIntegerField(help_text='1 = Trim/Semestre 1, 2 = Trim/Semestre 2, 3 = Trim/Semestre 3')),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_clotures', to='academics.classe')),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_clotures', to='academics.professeur')),
            ],
            options={
                'verbose_name': 'Clôture de notes période',
                'verbose_name_plural': 'Clôtures de notes périodes',
                'ordering': ['-periode'],
                'unique_together': {('classe', 'professeur', 'periode')},
            },
        ),
    ]
