# Generated by Django 5.2.3 on 2026-04-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0008_add_note_periode_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Maternelle 1', 'Maternelle 1'), ('Maternelle 2', 'Maternelle 2'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nde', '2nde'), ('1re', '1re'), ('Tle', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=20, verbose_name='Niveau de classe'),
        ),
    ]
