# Generated by Django 5.2.13 on 2026-04-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_active', models.BooleanField(default=False, verbose_name='Année active')),
                ('type_cycle_actif', models.CharField(blank=True, choices=[('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], max_length=20, null=True, verbose_name='Type de cycle actif')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('directeur', models.CharField(blank=True, max_length=100, verbose_name='Directeur')),
            ],
            options={
                'verbose_name': "Configuration de l'établissement",
                'verbose_name_plural': "Configurations de l'établissement",
            },
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('maternelle_1', 'Maternelle 1'), ('maternelle_2', 'Maternelle 2'), ('maternelle_3', 'Maternelle 3'), ('cp', 'Cours Préparatoire'), ('ce1', 'Cours Élémentaire 1'), ('ce2', 'Cours Élémentaire 2'), ('cm1', 'Cours Moyen 1'), ('cm2', 'Cours Moyen 2'), ('6e', 'Sixième'), ('5e', 'Cinquième'), ('4e', 'Quatrième'), ('3e', 'Troisième'), ('2nde', 'Seconde'), ('1re', 'Première'), ('tle', 'Terminale'), ('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'), ('m1', 'Master 1'), ('m2', 'Master 2')], max_length=20, unique=True, verbose_name='Niveau')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
                'verbose_name_plural': 'Niveaux scolaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(choices=[('trimestre', 'Trimestre'), ('semestre', 'Semestre')], max_length=20, verbose_name='Type de période')),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro')),
                ('debut', models.DateField(verbose_name='Date de début')),
                ('fin', models.DateField(verbose_name='Date de fin')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_evaluation', to='core.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': "Période d'évaluation",
                'verbose_name_plural': "Périodes d'évaluation",
                'ordering': ['annee_scolaire', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cycle', models.CharField(choices=[('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], max_length=20, verbose_name='Type de cycle')),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('pourcentage', models.PositiveIntegerField(default=100, help_text='Pourcentage du montant total à payer')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='core.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['annee_scolaire', 'type_cycle', 'numero'],
                'unique_together': {('annee_scolaire', 'type_cycle', 'numero')},
            },
        ),
    ]
