# Generated by Django 5.2.13 on 2026-04-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('type_contrat', models.CharField(choices=[('cdi', 'Contrat à durée indéterminée'), ('cdd', 'Contrat à durée déterminée'), ('stage', 'Stage'), ('interim', 'Intérim')], max_length=20, verbose_name='Type de contrat')),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('exigences', models.TextField(blank=True, verbose_name='Exigences du poste')),
                ('est_active', models.BooleanField(default=True, verbose_name='Poste actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fiche de poste',
                'verbose_name_plural': 'Fiches de postes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MembrePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(choices=[('direction', 'Direction'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignant'), ('surveillance', 'Surveillance'), ('agent_securite', 'Agent de Sécurité'), ('chauffeur', 'Chauffeur'), ('responsable_stock', 'Responsable Stock'), ('menage', "Agent d'entretien/Ménage"), ('medecin', 'Médecin/Infirmier'), ('autre', 'Autre')], max_length=25, verbose_name='Fonction')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='ressources_humaines.ficheposte', verbose_name='Poste')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Membres du personnel',
                'ordering': ['fonction', 'utilisateur__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ContratEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('cdi', 'Contrat à durée indéterminée'), ('cdd', 'Contrat à durée déterminée'), ('stage', 'Stage'), ('interim', 'Intérim')], max_length=20, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut mensuel')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions particulières')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='ressources_humaines.ficheposte')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='ressources_humaines.membrepersonnel')),
            ],
            options={
                'verbose_name': 'Contrat employé',
                'verbose_name_plural': 'Contrats employés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut')),
                ('retenue_cnps', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retenue CNPS')),
                ('retenue_irpp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retenue IRPP')),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres retenues')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('date_versement', models.DateField(blank=True, null=True, verbose_name='Date de versement')),
                ('est_paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='ressources_humaines.membrepersonnel', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Salaire',
                'verbose_name_plural': 'Salaires',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50, verbose_name='Période')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='fiches_paie/', verbose_name='Fichier PDF')),
                ('salaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_paie', to='ressources_humaines.salaire', verbose_name='Salaire')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-date_generation'],
            },
        ),
    ]
