# Generated by Django 5.2.13 on 2026-04-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources_humaines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('jours_annuels', models.PositiveIntegerField(default=0, verbose_name='Jours alloués par an')),
                ('est_paye', models.BooleanField(default=True, verbose_name='Est payé')),
                ('est_deductible', models.BooleanField(default=False, verbose_name='Déductible des jours')),
                ('couleur', models.CharField(default='#4472C4', max_length=7, verbose_name='Couleur')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('maladie', 'Maladie'), ('accident', 'Accident'), ('famille', 'Famille'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('date_absence', models.DateField(verbose_name='Date')),
                ('heures', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Heures d'absence")),
                ('est_justifiee', models.BooleanField(default=False, verbose_name='Justifiée')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('document', models.FileField(blank=True, null=True, upload_to='absences/', verbose_name='Justificatif')),
                ('statut', models.CharField(choices=[('non_justifiee', 'Non justifiée'), ('justifiee', 'Justifiée'), ('en_cours', 'En cours de traitement')], default='non_justifiee', max_length=20, verbose_name='Statut')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='ressources_humaines.membrepersonnel', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_absence'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('jours', models.PositiveIntegerField(verbose_name='Nombre de jours')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='ressources_humaines.membrepersonnel', verbose_name='Employé')),
                ('remplissant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_remplacement', to='ressources_humaines.membrepersonnel', verbose_name='Remplaçant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources_humaines.typeconge', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('jours_pris', models.PositiveIntegerField(default=0, verbose_name='Jours pris')),
                ('jours_restants', models.PositiveIntegerField(verbose_name='Jours restants')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conges', to='ressources_humaines.membrepersonnel', verbose_name='Employé')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources_humaines.typeconge', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Solde de congés',
                'verbose_name_plural': 'Soldes de congés',
                'unique_together': {('employe', 'annee', 'type_conge')},
            },
        ),
    ]
