from django.urls import path
from . import views

app_name = 'academics'

urlpatterns = [
    path('classes/', views.classe_list_view, name='classe_list'),
    path('classes/ajouter/', views.classe_create_view, name='classe_create'),
    path('classes/<int:pk>/modifier/', views.classe_edit_view, name='classe_edit'),
    path('classes/<int:pk>/supprimer/', views.classe_delete_view, name='classe_delete'),
    path('matieres/', views.matiere_list_view, name='matiere_list'),
    path('matieres/ajouter/', views.matiere_create_view, name='matiere_create'),
    path('matieres/<int:pk>/', views.matiere_edit_view, name='matiere_edit'),
    path('matieres/<int:pk>/supprimer/', views.matiere_delete_view, name='matiere_delete'),
    path('professeurs/', views.professeur_list_view, name='professeur_list'),
    path('professeurs/ajouter/', views.professeur_create_view, name='professeur_create'),
    path('professeurs/<int:pk>/modifier/', views.professeur_edit_view, name='professeur_edit'),
    path('professeurs/<int:pk>/supprimer/', views.professeur_delete_view, name='professeur_delete'),
    path('attributions/', views.attribution_list_view, name='attribution_list'),
    path('attributions/ajouter/', views.attribution_list_view, name='attribution_create'),
    path('attributions/<int:pk>/modifier/', views.attribution_edit_view, name='attribution_edit'),
    path('attributions/<int:pk>/supprimer/', views.attribution_delete_view, name='attribution_delete'),
    path('mes-classes/', views.mes_classes_view, name='mes_classes'),
    path('evaluations/ajouter/', views.saisie_notes_detail_view, name='evaluation_create'),
    path('evaluations/<int:pk>/modifier/', views.evaluation_edit_view, name='evaluation_edit'),
    path('evaluations/<int:pk>/supprimer/', views.evaluation_delete_view, name='evaluation_delete'),
    path('saisie-notes/', views.saisie_notes_detail_view, name='saisie_notes'),
    path('saisie-notes/<int:classe_pk>/', views.saisie_notes_detail_view, name='saisie_notes_classe'),
    path('saisie-notes/<int:classe_pk>/<int:matiere_pk>/', views.saisie_notes_detail_view, name='saisie_notes_detail'),
    path('feuille-notes/<int:classe_pk>/', views.releve_notes_view, name='feuille_notes'),
    path('statistiques/<int:classe_pk>/', views.bulletin_view, name='statistiques_classe'),
    path('bulletin-classe/<int:classe_pk>/', views.bulletin_view, name='bulletin_classe'),
    path('bulletin/eleve/<int:eleve_pk>/', views.bulletin_eleve_view, name='bulletin_eleve'),
    path('bulletin/eleve/<int:eleve_pk>/imprimer/', views.bulletin_imprimable_view, name='bulletin_imprimable'),
    path('fiche-notes/<int:classe_pk>/', views.bulletin_view, name='classe_fiche_notes'),
    path('historique-notes/', views.releve_notes_view, name='historique_notes'),
    path('historique-notes/<int:classe_pk>/', views.releve_notes_view, name='historique_notes_classe'),
    path('fiches-notes/', views.saisie_notes_detail_view, name='fiche_notes_list'),
    path('fiche-note/eleve/<int:eleve_pk>/', views.eleve_list, name='fiche_note_eleve'),
    path('fiche-note/eleve/<int:eleve_pk>/<int:cycle_pk>/<int:matiere_pk>/', views.fiche_note_detail_view, name='fiche_note_detail'),
    path('emploi-du-temps/', views.emploi_du_temps_view, name='emploi_du_temps'),
    path('emploi-du-temps/reinitialiser/', views.emploi_du_temps_reset_view, name='reinitialiser_emploi_temps'),
    path('salles/', views.salle_list_view, name='salle_list'),
    path('salles/ajouter/', views.salle_create_view, name='salle_create'),
    path('salles/<int:pk>/modifier/', views.salle_edit_view, name='salle_edit'),
    path('salles/<int:pk>/supprimer/', views.salle_delete_view, name='salle_delete'),
    path('examens/', views.examen_list_view, name='examen_list'),
    path('examens/ajouter/', views.examen_create_view, name='examen_create'),
    path('examens/<int:pk>/', views.examen_edit_view, name='examen_edit'),
    path('examens/<int:pk>/detail/', views.examen_detail_view, name='examen_detail'),
    path('examens/<int:pk>/supprimer/', views.examen_delete_view, name='examen_delete'),
    path('examens/<int:pk>/publier/', views.examen_publish_view, name='examen_publier'),
    path('examens/<int:pk>/generer-epreuves/', views.examen_schedule_view, name='examen_generate_epreuves'),
    path('contraintes/', views.contrainte_list_view, name='contrainte_list'),
    path('contraintes/ajouter/', views.contrainte_create_view, name='contrainte_create'),
    path('contraintes/<int:pk>/modifier/', views.contrainte_edit_view, name='contrainte_edit'),
    path('contraintes/<int:pk>/supprimer/', views.contrainte_delete_view, name='contrainte_delete'),
]
