# Generated by Django 6.0.3 on 2026-04-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('eleves', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='finances.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='academics.classe')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.matiere')),
                ('professeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.professeur')),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
                'unique_together': {('classe', 'date', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_appel', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard')], max_length=20)),
                ('motif_absence', models.TextField(blank=True)),
                ('justifie', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='finances.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='academics.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.professeur')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'eleve__nom'],
                'unique_together': {('eleve', 'date')},
            },
        ),
    ]
