# Generated by Django 5.2.13 on 2026-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_professeur_salaire_base'),
        ('eleves', '0009_eleve_niveau'),
        ('presences', '0002_seancecours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'classe', 'date')},
        ),
    ]
