# Generated by Django 5.2.13 on 2026-04-18 09:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReinitialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Code de réinitialisation',
                'verbose_name_plural': 'Codes de réinitialisation',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du groupe')),
                ('is_groupe', models.BooleanField(default=False, verbose_name='Est un groupe')),
                ('type_conversation', models.CharField(choices=[('individuel', 'Conversation individuelle'), ('groupe', 'Conversation de groupe'), ('service', 'Message au service')], default='individuel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeApprobation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('type_objet', models.CharField(choices=[('eleve', 'Élève'), ('document', 'Document'), ('salaire', 'Salaire'), ('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('paiement', 'Paiement'), ('matiere', 'Matière'), ('classe', 'Classe'), ('attribution', 'Attribution matière'), ('contrainte', 'Contrainte horaire'), ('frais', 'Frais scolaires'), ('emploi_temps', 'Emploi du temps'), ('charge', 'Charge'), ('personnel', 'Personnel'), ('professeur', 'Professeur'), ('autre', 'Autre')], max_length=20)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objet_repr', models.CharField(max_length=255, verbose_name='Objet concerné')),
                ('details', models.TextField(verbose_name='Détails de la demande')),
                ('details_avant', models.TextField(blank=True, verbose_name='État avant modification')),
                ('details_apos', models.TextField(blank=True, verbose_name='État après modification')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de la demande')),
                ('observations', models.TextField(blank=True, verbose_name="Observations de l'approbateur")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Demande d'approbation",
                'verbose_name_plural': "Demandes d'approbation",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('direction', 'Direction'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Professeur'), ('surveillance', 'Surveillance')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=20)),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=255, verbose_name='Objet')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('annee_scolaire', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('individuel', 'Message individuel'), ('groupe', 'Message de groupe'), ('service', 'Message au service')], default='individuel', max_length=20)),
                ('service', models.CharField(blank=True, choices=[('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision')], max_length=20)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du module')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code unique')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('icon', models.CharField(default='bi bi-folder', max_length=50, verbose_name='Icône')),
                ('type_module', models.CharField(choices=[('menu', 'Menu principal'), ('sous_menu', 'Sous-menu')], default='menu', max_length=20, verbose_name='Type')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['service', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('compte_attente', 'Compte en attente'), ('compte_approuve', 'Compte approuvé'), ('compte_refuse', 'Compte refusé'), ('absence_eleve', 'Absence élève'), ('retard_eleve', 'Retard élève'), ('debut_cours', 'Début de cours'), ('fin_cours', 'Fin de cours'), ('paiement_recu', 'Paiement reçu'), ('frais_impaye', 'Frais impayé'), ('message', 'Nouveau message'), ('securite', 'Alerte sécurité'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Rôle')),
                ('actions', models.JSONField(default=list, verbose_name='Actions autorisées')),
                ('niveau', models.CharField(choices=[('aucun', 'Aucun accès'), ('lecture', 'Lecture seule'), ('lecture_ecriture', 'Lecture et écriture'), ('complet', 'Accès complet'), ('admin', 'Administration')], default='lecture', max_length=20, verbose_name='Niveau de permission')),
                ('require_approval', models.BooleanField(default=False, verbose_name='Exige approbation pour modifications')),
                ('approbateurs', models.JSONField(default=list, verbose_name='Rôles approbateurs')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Rôle')),
                ('actions_avant', models.JSONField(default=list, verbose_name='Actions avant modification')),
                ('actions_apres', models.JSONField(default=list, verbose_name='Actions après modification')),
                ('niveau_avant', models.CharField(blank=True, max_length=20, verbose_name='Niveau avant')),
                ('niveau_apres', models.CharField(blank=True, max_length=20, verbose_name='Niveau après')),
                ('type_modification', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20, verbose_name='Type de modification')),
                ('motif', models.TextField(verbose_name='Motif de la modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('commentaire', models.TextField(blank=True, verbose_name="Commentaire de l'approbateur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Modification de permission',
                'verbose_name_plural': 'Modifications de permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionPersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField(default=list, verbose_name='Actions autorisées')),
                ('niveau', models.CharField(choices=[('aucun', 'Aucun accès'), ('lecture', 'Lecture'), ('write', 'Écriture'), ('complet', 'Complet')], default='lecture', max_length=20, verbose_name='Niveau')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_temporaire', models.BooleanField(default=False, verbose_name='Permission temporaire')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Permission personnalisée',
                'verbose_name_plural': 'Permissions personnalisées',
            },
        ),
        migrations.CreateModel(
            name='ProfilPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du profil de permissions')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('roles_cibles', models.JSONField(default=list, verbose_name='Rôles cibles par défaut')),
            ],
            options={
                'verbose_name': 'Profil de permissions',
                'verbose_name_plural': 'Profils de permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, unique=True, verbose_name='Rôle')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name="Nombre max d'utilisateurs")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Quota par rôle',
                'verbose_name_plural': 'Quotas par rôle',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='bi bi-folder', max_length=50, verbose_name='Icône')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TentativeConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lock_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrateur'), ('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision'), ('agent_securite', 'Agent de Sécurité'), ('responsable_stock', 'Responsable Stock'), ('chauffeur', 'Chauffeur')], max_length=25)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Compte approuvé')),
                ('totp_secret', models.CharField(blank=True, max_length=32, verbose_name='Secret TOTP')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='Authentification 2FA activée')),
                ('is_2fa_required', models.BooleanField(default=False, verbose_name='2FA obligatoire (Direction/Comptabilité)')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Codes de secours')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
