# Generated by Django 5.2.13 on 2026-04-18 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentification', '0001_initial'),
        ('enseignement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='enseignement.matiere', verbose_name='Matière enseignée'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='codereinitialisation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeapprobation',
            name='approbateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeapprobation',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentification.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentification.groupe'),
        ),
        migrations.AddField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_modules', to='authentification.module', verbose_name='Module parent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authentification.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='permissionmodification',
            name='approbateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='permissionmodification',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AddField(
            model_name='permissionmodification',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='permissionmodification',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='authentification.permission'),
        ),
        migrations.AddField(
            model_name='permissionpersonnalisee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='permissionpersonnalisee',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='permissionpersonnalisee',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_modules', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='profilpermission',
            name='modules',
            field=models.ManyToManyField(related_name='profils', to='authentification.module', verbose_name='Modules autorisés'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profils_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='authentification.profilpermission', verbose_name='Profils de permissions'),
        ),
        migrations.AddField(
            model_name='module',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='authentification.service', verbose_name='Service'),
        ),
        migrations.AlterUniqueTogether(
            name='tentativeconnexion',
            unique_together={('username', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='permissionpersonnalisee',
            unique_together={('utilisateur', 'module')},
        ),
    ]
