# Generated by Django 4.2.11 on 2026-04-01 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('compte_attente', 'Compte en attente'), ('compte_approuve', 'Compte approuvé'), ('compte_refuse', 'Compte refusé'), ('absence_eleve', 'Absence élève'), ('retard_eleve', 'Retard élève'), ('debut_cours', 'Début de cours'), ('fin_cours', 'Fin de cours'), ('paiement_recu', 'Paiement reçu'), ('frais_impaye', 'Frais impayé'), ('message', 'Nouveau message'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('individuel', 'Message individuel'), ('groupe', 'Message de groupe'), ('service', 'Message au service')], default='individuel', max_length=20)),
                ('service', models.CharField(blank=True, choices=[('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentification.groupe')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
