# Generated by Django 4.2.11 on 2026-04-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_user_role_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
