# Generated by Django 5.2.3 on 2026-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_add_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision'), ('agent_securite', 'Agent de Sécurité'), ('responsable_stock', 'Responsable Stock'), ('chauffeur', 'Chauffeur')], max_length=25),
        ),
    ]
