# Generated by Django 5.2.3 on 2026-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_demande_approbation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Codes de secours'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='Authentification 2FA activée'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_required',
            field=models.BooleanField(default=False, verbose_name='2FA obligatoire (Direction/Comptabilité)'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, verbose_name='Secret TOTP'),
        ),
        migrations.AlterField(
            model_name='demandeapprobation',
            name='type_objet',
            field=models.CharField(choices=[('eleve', 'Élève'), ('salaire', 'Salaire'), ('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('paiement', 'Paiement'), ('matiere', 'Matière'), ('classe', 'Classe'), ('attribution', 'Attribution matière'), ('frais', 'Frais scolaires'), ('emploi_temps', 'Emploi du temps'), ('charge', 'Charge'), ('personnel', 'Personnel')], max_length=20),
        ),
    ]
