# Generated by Django 5.2.3 on 2026-04-05 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_rolequota'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navigateur')),
                ('attempts', models.PositiveIntegerField(default=1, verbose_name='Tentatives')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Bloqué jusqu'à")),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Dernière tentative')),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('compte_attente', 'Compte en attente'), ('compte_approuve', 'Compte approuvé'), ('compte_refuse', 'Compte refusé'), ('absence_eleve', 'Absence élève'), ('retard_eleve', 'Retard élève'), ('debut_cours', 'Début de cours'), ('fin_cours', 'Fin de cours'), ('paiement_recu', 'Paiement reçu'), ('frais_impaye', 'Frais impayé'), ('message', 'Nouveau message'), ('securite', 'Alerte sécurité'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de réinitialisation',
                'verbose_name_plural': 'Codes de réinitialisation',
            },
        ),
    ]
