# Generated by Django 5.2.3 on 2026-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_loginattempt_alter_notification_type_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='lock_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de blocages'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Tentatives du cycle'),
        ),
    ]
