# Generated by Django 5.2.3 on 2026-04-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_loginattempt_lock_count_alter_loginattempt_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeapprobation',
            old_name='details_apres',
            new_name='details_apos',
        ),
        migrations.AlterField(
            model_name='demandeapprobation',
            name='type_objet',
            field=models.CharField(choices=[('eleve', 'Élève'), ('salaire', 'Salaire'), ('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('paiement', 'Paiement'), ('matiere', 'Matière'), ('classe', 'Classe'), ('attribution', 'Attribution matière'), ('frais', 'Frais scolaires'), ('emploi_temps', 'Emploi du temps'), ('charge', 'Charge'), ('personnel', 'Personnel'), ('professeur', 'Professeur'), ('autre', 'Autre')], max_length=20),
        ),
    ]
