# Generated by Django 5.2.3 on 2026-04-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_professeur_salaire_base'),
        ('authentification', '0018_permission_approbateurs_permission_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='academics.matiere', verbose_name='Matière (pour enseignements)'),
        ),
    ]
