# Generated by Django 4.2.11 on 2026-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message_conversation_id_alter_message_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='user',
            name='salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire de base (FCFA)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='service',
            field=models.CharField(blank=True, choices=[('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision'), ('agent_securite', 'Agent de Sécurité'), ('responsable_stock', 'Responsable Stock'), ('chauffeur', 'Chauffeur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('direction', 'Direction générale'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignement'), ('surveillance', 'Contrôle & Supervision'), ('agent_securite', 'Agent de Sécurité'), ('responsable_stock', 'Responsable Stock'), ('chauffeur', 'Chauffeur')], max_length=25),
        ),
    ]
