# Generated by Django 4.2.11 on 2026-04-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_date_embauche_user_salaire_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=20)),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=255, verbose_name='Objet')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('annee_scolaire', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='logconnexion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expediteur',
        ),
        migrations.DeleteModel(
            name='LogAction',
        ),
        migrations.DeleteModel(
            name='LogConnexion',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
