# Generated by Django 5.2.3 on 2026-04-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_message_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeApprobation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('type_objet', models.CharField(choices=[('eleve', 'Élève'), ('salaire', 'Salaire'), ('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('paiement', 'Paiement')], max_length=20)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objet_repr', models.CharField(max_length=255, verbose_name='Objet concerné')),
                ('details', models.TextField(verbose_name='Détails de la demande')),
                ('details_avant', models.TextField(blank=True, verbose_name='État avant modification')),
                ('details_apres', models.TextField(blank=True, verbose_name='État après modification')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de la demande')),
                ('observations', models.TextField(blank=True, verbose_name="Observations de l'approbateur")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('approbateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'approbation",
                'verbose_name_plural': "Demandes d'approbation",
                'ordering': ['-date_creation'],
            },
        ),
    ]
