# Generated by Django 5.2.3 on 2026-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_2fa_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, unique=True, verbose_name='Rôle')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name="Nombre max d'utilisateurs")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Quota par rôle',
                'verbose_name_plural': 'Quotas par rôle',
            },
        ),
    ]
