# Generated by Django 5.2.3 on 2026-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_details_apos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeapprobation',
            name='type_objet',
            field=models.CharField(choices=[('eleve', 'Élève'), ('document', 'Document'), ('salaire', 'Salaire'), ('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('paiement', 'Paiement'), ('matiere', 'Matière'), ('classe', 'Classe'), ('attribution', 'Attribution matière'), ('frais', 'Frais scolaires'), ('emploi_temps', 'Emploi du temps'), ('charge', 'Charge'), ('personnel', 'Personnel'), ('professeur', 'Professeur'), ('autre', 'Autre')], max_length=20),
        ),
    ]
