# Generated by Django 5.2.3 on 2026-04-07 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_demandeapprobation_type_objet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='bi bi-folder', max_length=50, verbose_name='Icône')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='demandeapprobation',
            name='type_objet',
            field=models.CharField(choices=[('eleve', 'Élève'), ('document', 'Document'), ('salaire', 'Salaire'), ('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('paiement', 'Paiement'), ('matiere', 'Matière'), ('classe', 'Classe'), ('attribution', 'Attribution matière'), ('contrainte', 'Contrainte horaire'), ('frais', 'Frais scolaires'), ('emploi_temps', 'Emploi du temps'), ('charge', 'Charge'), ('personnel', 'Personnel'), ('professeur', 'Professeur'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du module')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code unique')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('icon', models.CharField(default='bi bi-folder', max_length=50, verbose_name='Icône')),
                ('type_module', models.CharField(choices=[('menu', 'Menu principal'), ('sous_menu', 'Sous-menu')], default='menu', max_length=20, verbose_name='Type')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_modules', to='accounts.module', verbose_name='Module parent')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['service', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du profil de permissions')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('roles_cibles', models.JSONField(default=list, verbose_name='Rôles cibles par défaut')),
                ('modules', models.ManyToManyField(related_name='profils', to='accounts.module', verbose_name='Modules autorisés')),
            ],
            options={
                'verbose_name': 'Profil de permissions',
                'verbose_name_plural': 'Profils de permissions',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='modules_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='accounts.modulepermission', verbose_name='Permissions modules'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Rôle')),
                ('actions', models.JSONField(default=list, verbose_name='Actions autorisées')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'unique_together': {('module', 'role')},
            },
        ),
    ]
