# Generated by Django 5.2.3 on 2026-04-07 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_service_alter_demandeapprobation_type_objet_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='approbateurs',
            field=models.JSONField(default=list, verbose_name='Rôles approbateurs'),
        ),
        migrations.AddField(
            model_name='permission',
            name='niveau',
            field=models.CharField(choices=[('aucun', 'Aucun accès'), ('lecture', 'Lecture seule'), ('lecture_ecriture', 'Lecture et écriture'), ('complet', 'Accès complet'), ('admin', 'Administration')], default='lecture', max_length=20, verbose_name='Niveau de permission'),
        ),
        migrations.AddField(
            model_name='permission',
            name='require_approval',
            field=models.BooleanField(default=False, verbose_name='Exige approbation pour modifications'),
        ),
        migrations.CreateModel(
            name='PermissionModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Rôle')),
                ('actions_avant', models.JSONField(default=list, verbose_name='Actions avant modification')),
                ('actions_apres', models.JSONField(default=list, verbose_name='Actions après modification')),
                ('niveau_avant', models.CharField(blank=True, max_length=20, verbose_name='Niveau avant')),
                ('niveau_apres', models.CharField(blank=True, max_length=20, verbose_name='Niveau après')),
                ('type_modification', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20, verbose_name='Type de modification')),
                ('motif', models.TextField(verbose_name='Motif de la modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('commentaire', models.TextField(blank=True, verbose_name="Commentaire de l'approbateur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('approbateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module', verbose_name='Module')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='accounts.permission')),
            ],
            options={
                'verbose_name': 'Modification de permission',
                'verbose_name_plural': 'Modifications de permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField(default=list, verbose_name='Actions autorisées')),
                ('niveau', models.CharField(choices=[('aucun', 'Aucun accès'), ('lecture', 'Lecture'), ('write', 'Écriture'), ('complet', 'Complet')], default='lecture', max_length=20, verbose_name='Niveau')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_temporaire', models.BooleanField(default=False, verbose_name='Permission temporaire')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module', verbose_name='Module')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_modules', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateurs',
                'unique_together': {('utilisateur', 'module')},
            },
        ),
    ]
