# Generated by Django 6.0.3 on 2026-04-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rang', models.PositiveIntegerField(default=0)),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('appreciation', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.inscription')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-date_generation'],
            },
        ),
    ]
