# Generated by Django 5.2.13 on 2026-04-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rang', models.PositiveIntegerField(default=0)),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('appreciation', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='core.cycle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='scolarite.eleve')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='scolarite.eleveinscription')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-date_generation'],
            },
        ),
    ]
