# Generated by Django 4.2.11 on 2026-04-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_add_mode_application_frais'),
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='finances.cycleconfig'),
        ),
    ]
