# Generated by Django 5.2.13 on 2026-04-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_add_new_modules'),
        ('rapports', '0002_bulletin_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='finances.cycleconfig'),
        ),
    ]
