# Generated by Django 5.2.13 on 2026-04-18 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_eval', models.CharField(choices=[('interrogation', 'Interrogation'), ('devoir', 'Devoir surveillé'), ('examen', 'Examen'), ('autre', 'Autre')], default='interrogation', max_length=20)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('date_eval', models.DateField()),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_examen', models.DateField()),
                ('duree_minutes', models.PositiveIntegerField(default=60)),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('est_publie', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='FicheNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rang', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Fiche de note',
                'verbose_name_plural': 'Fiches de notes',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Profil Professeur',
                'verbose_name_plural': 'Profils Professeurs',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_salle', models.CharField(choices=[('classe', 'Salle de classe'), ('laboratoire', 'Laboratoire'), ('informatique', 'Salle informatique'), ('sport', 'Salle de sport'), ('bibliotheque', 'Bibliothèque'), ('autre', 'Autre')], default='classe', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=40)),
                ('etage', models.CharField(blank=True, help_text='Ex: RDC, 1er étage', max_length=20)),
                ('equipements', models.TextField(blank=True, help_text='Vidéoprojecteur, tableau interactif, etc.')),
                ('est_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('serie', models.CharField(blank=True, max_length=10, verbose_name='Série (Lycée)')),
                ('domaine', models.CharField(blank=True, max_length=50, verbose_name='Domaine (Université)')),
                ('subdivision', models.CharField(blank=True, max_length=50, verbose_name='Subdivision (ex: 1, 2, A, B...)')),
                ('capacite', models.PositiveIntegerField(default=40)),
                ('note_conduite_base', models.PositiveIntegerField(default=20)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.anneescolaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.niveauscolaire', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='core.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='enseignement.classe')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
            },
        ),
        migrations.CreateModel(
            name='CoefficientMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='enseignement.classe')),
            ],
            options={
                'verbose_name': 'Coefficient',
                'verbose_name_plural': 'Coefficients',
            },
        ),
        migrations.CreateModel(
            name='ContrainteHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_contrainte', models.CharField(max_length=20)),
                ('statut', models.CharField(default='approuve', max_length=20)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='core.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='enseignement.classe')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='core.periodeevaluation')),
            ],
            options={
                'verbose_name': 'Contrainte horaire',
                'verbose_name_plural': 'Contraintes horaires',
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('est_corrige', models.BooleanField(default=False)),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
            },
        ),
    ]
