# Generated by Django 5.2.13 on 2026-04-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('enseignement', '0001_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='scolarite.eleve'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='enseignement.classe'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='scolarite.eleve'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.periodeevaluation'),
        ),
        migrations.AddField(
            model_name='examen',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='core.anneescolaire'),
        ),
        migrations.AddField(
            model_name='examen',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='enseignement.classe'),
        ),
        migrations.AddField(
            model_name='examen',
            name='surveillant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='enseignement.examen'),
        ),
        migrations.AddField(
            model_name='fichenote',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_notes', to='enseignement.classe'),
        ),
        migrations.AddField(
            model_name='fichenote',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_notes', to='scolarite.eleve'),
        ),
        migrations.AddField(
            model_name='fichenote',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_notes', to='core.periodeevaluation'),
        ),
        migrations.AddField(
            model_name='examen',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='enseignement.matiere'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='enseignement.matiere'),
        ),
        migrations.AddField(
            model_name='coefficientmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='enseignement.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(related_name='classes', through='enseignement.CoefficientMatiere', to='enseignement.matiere'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='enseignement.matiere'),
        ),
        migrations.AddField(
            model_name='profilprofesseur',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialistes', to='enseignement.matiere'),
        ),
        migrations.AddField(
            model_name='profilprofesseur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_professeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contraintehoraire',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='enseignement.profilprofesseur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='enseignement.profilprofesseur'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='enseignement.profilprofesseur'),
        ),
        migrations.AddField(
            model_name='examen',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enseignement.salle'),
        ),
        migrations.AlterUniqueTogether(
            name='epreuve',
            unique_together={('examen', 'eleve')},
        ),
        migrations.AlterUniqueTogether(
            name='coefficientmatiere',
            unique_together={('classe', 'matiere')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'serie', 'domaine', 'subdivision', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='attribution',
            unique_together={('professeur', 'classe', 'matiere', 'annee_scolaire')},
        ),
    ]
