# Generated by Django 5.2.13 on 2026-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, verbose_name='Coefficient'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'coefficient')},
        ),
    ]
