# Generated by Django 5.2.13 on 2026-04-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('enseignement', '0002_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BourseRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bourse/Remise',
                'verbose_name_plural': 'Bourses/Remises',
            },
        ),
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
            },
        ),
        migrations.CreateModel(
            name='ChargeFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_charge', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet'), ('assurance', 'Assurance'), ('impots', 'Impôts et Taxes'), ('maintenance', 'Maintenance'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodicite', models.CharField(default='mensuelle', max_length=20)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Charge fixe',
                'verbose_name_plural': 'Charges fixes',
            },
        ),
        migrations.CreateModel(
            name='ChargeOperationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_charge', models.DateField()),
                ('type_charge', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet'), ('assurance', 'Assurance'), ('impots', 'Impôts et Taxes'), ('maintenance', 'Maintenance'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('est_payee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Charge opérationnelle',
                'verbose_name_plural': 'Charges opérationnelles',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('scolarite', 'Frais de scolarité'), ('bibliotheque', 'Bibliothèque'), ('activites', 'Activités'), ('transport', 'Transport'), ('cantine', 'Cantine'), ('autre', 'Autre')], max_length=20)),
                ('mode_application', models.CharField(choices=[('general', 'Toutes les classes'), ('niveau', 'Par niveau/filière'), ('detaille', 'Classes spécifiques')], default='detaille', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='core.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='enseignement.classe')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveauscolaire')),
            ],
            options={
                'verbose_name': 'Frais scolaire',
                'verbose_name_plural': 'Frais scolaires',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('type_operation', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement')], max_length=20)),
                ('categorie', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiaire', models.CharField(blank=True, max_length=200)),
                ('motif', models.TextField()),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opération de caisse',
                'verbose_name_plural': 'Opérations de caisse',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='scolarite.eleve')),
                ('encaisse_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.fraisscolaire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RappelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField()),
                ('montant_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(default='envoye', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Rappel de paiement',
                'verbose_name_plural': 'Rappels de paiements',
            },
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('total_recettes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_depenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneescolaire')),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
            },
        ),
        migrations.CreateModel(
            name='EleveBourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneescolaire')),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.bourseremise')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bourses', to='scolarite.eleve')),
            ],
            options={
                'verbose_name': 'Élève boursier',
                'verbose_name_plural': 'Élèves boursiers',
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
