# Generated by Django 6.0.3 on 2026-04-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EcoleCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('type_operation', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement')], max_length=20)),
                ('categorie', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiaire', models.CharField(blank=True, max_length=200)),
                ('motif', models.TextField()),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opération de caisse',
                'verbose_name_plural': 'Opérations de caisse',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('scolarite', 'Frais de scolarité'), ('bibliotheque', 'Bibliothèque'), ('activites', 'Activités'), ('transport', 'Transport'), ('cantine', 'Cantine')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='finances.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academics.classe')),
            ],
            options={
                'verbose_name': 'Frais scolaire',
                'verbose_name_plural': 'Frais scolaires',
                'unique_together': {('classe', 'type_frais', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.fraisscolaire')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(max_length=50)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('montant_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('acquitte', 'Acquitté'), ('annule', 'Annulé')], default='envoye', max_length=20)),
                ('date_acquittement', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.PositiveIntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salaire',
                'verbose_name_plural': 'Salaires',
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
    ]
