# Generated by Django 4.2.11 on 2026-04-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fraisscolaire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fraisscolaire',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fraisscolaire',
            name='type_frais',
            field=models.CharField(choices=[('inscription', "Frais d'inscription"), ('scolarite', 'Frais de scolarité'), ('bibliotheque', 'Bibliothèque'), ('activites', 'Activités'), ('transport', 'Transport'), ('cantine', 'Cantine'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='fraisscolaire',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='fraisscolaire',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='fraisscolaire',
            name='echeance',
        ),
    ]
