# Generated by Django 4.2.11 on 2026-04-02 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_fraisscolaire_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cycle', models.CharField(choices=[('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('pourcentage', models.PositiveIntegerField(default=100, help_text='Pourcentage du montant total à payer')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='finances.anneescolaire')),
            ],
            options={
                'verbose_name': 'Configuration du cycle',
                'verbose_name_plural': 'Configurations des cycles',
                'ordering': ['annee_scolaire', 'type_cycle', 'numero'],
                'unique_together': {('annee_scolaire', 'type_cycle', 'numero')},
            },
        ),
    ]
