# Generated by Django 4.2.11 on 2026-04-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_matiere_unique_together'),
        ('finances', '0003_cycleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisscolaire',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='finances.anneescolaire'),
        ),
        migrations.AddField(
            model_name='fraisscolaire',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour tous les élèves', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academics.classe'),
        ),
    ]
