# Generated by Django 4.2.11 on 2026-04-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_fraisscolaire_annee_scolaire_fraisscolaire_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='type_cycle_actif',
            field=models.CharField(blank=True, choices=[('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], help_text='Type de cycle actif pour cette année scolaire', max_length=20, null=True),
        ),
    ]
