# Generated by Django 4.2.11 on 2026-04-02 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0005_anneescolaire_type_cycle_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_charge', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet'), ('assurance', 'Assurance'), ('impots', 'Impôts et Taxes'), ('maintenance', 'Maintenance'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle')], default='mensuelle', max_length=20)),
                ('beneficiaire', models.CharField(blank=True, help_text='Propriétaire, société, etc.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Charge fixe',
                'verbose_name_plural': 'Charges fixes',
                'ordering': ['type_charge', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ChargeOperationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_charge', models.DateField()),
                ('type_charge', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet'), ('assurance', 'Assurance'), ('impots', 'Impôts et Taxes'), ('maintenance', 'Maintenance'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Numéro de facture, reçu, etc.', max_length=100)),
                ('est_payee', models.BooleanField(default=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charge opérationnelle',
                'verbose_name_plural': 'Charges opérationnelles',
                'ordering': ['-date_charge'],
            },
        ),
    ]
