# Generated by Django 4.2.11 on 2026-04-02 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0006_chargefixe_chargeoperationnelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(choices=[('direction', 'Direction'), ('secretaire', 'Secrétariat'), ('comptable', 'Comptabilité'), ('professeur', 'Enseignant'), ('surveillance', 'Surveillance'), ('agent_securite', 'Agent de Sécurité'), ('chauffeur', 'Chauffeur'), ('responsable_stock', 'Responsable Stock'), ('menage', "Agent d'entretien/Ménage"), ('medecin', 'Médecin/Infirmier'), ('autre', 'Autre')], max_length=25)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('salaire_mensuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire mensuel (FCFA)')),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True)),
                ('compte_utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_personnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['fonction', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SalairePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.PositiveIntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('est_paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='finances.personnel')),
            ],
            options={
                'verbose_name': 'Salaire du personnel',
                'verbose_name_plural': 'Salaires du personnel',
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
    ]
