# Generated by Django 4.2.11 on 2026-04-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_matiere_unique_together'),
        ('finances', '0007_personnel_salairepersonnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisscolaire',
            name='filiere',
            field=models.CharField(blank=True, help_text='Filière spécifique (ex: A1, C, D). Laisser vide pour toutes les filières du niveau.', max_length=50),
        ),
        migrations.AddField(
            model_name='fraisscolaire',
            name='mode_application',
            field=models.CharField(choices=[('general', 'Toutes les classes'), ('niveau', 'Par niveau/filière'), ('detaille', 'Classes spécifiques')], default='detaille', max_length=20),
        ),
        migrations.AddField(
            model_name='fraisscolaire',
            name='niveau',
            field=models.CharField(blank=True, choices=[('CI', 'Cours Initial'), ('CP', 'Cours Préparatoire'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('6e', 'Sixième'), ('5e', 'Cinquième'), ('4e', 'Quatrième'), ('3e', 'Troisième'), ('2nde', 'Seconde'), ('1re', 'Première'), ('Tle', 'Terminale')], help_text="Pour mode 'Par niveau/filière'", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fraisscolaire',
            name='classe',
            field=models.ForeignKey(blank=True, help_text="Pour mode 'Classes spécifiques'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academics.classe'),
        ),
    ]
