# Generated by Django 4.2.11 on 2026-04-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_add_mode_application_frais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaire',
            options={'verbose_name': 'Salaire du personnel', 'verbose_name_plural': 'Salaires du personnel'},
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='statut',
        ),
        migrations.AddField(
            model_name='salaire',
            name='est_paye',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='finances.personnel'),
        ),
        migrations.DeleteModel(
            name='SalairePersonnel',
        ),
    ]
