# Generated by Django 5.2.3 on 2026-04-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_add_new_modules'),
        ('finances', '0009_alter_salaire_options_remove_salaire_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BourseRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_remise', models.CharField(choices=[('bourse', 'Bourse'), ('remise', 'Remise')], max_length=20)),
                ('pourcentage', models.DecimalField(decimal_places=2, help_text='Pourcentage de réduction', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bourse/Remise',
                'verbose_name_plural': 'Bourses/Remises',
                'ordering': ['-est_active', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('partiellement_payee', 'Partiellement payée'), ('en_attente', 'En attente'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='eleves.eleve')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='eleves.inscription')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, help_text='Remise en pourcentage', max_digits=5)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.facture')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.fraisscolaire')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('total_recettes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_depenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_salaires', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('details_recettes', models.JSONField(blank=True, default=dict)),
                ('details_depenses', models.JSONField(blank=True, default=dict)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.anneescolaire')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='EleveBourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_accorde', models.DecimalField(decimal_places=2, max_digits=5)),
                ('justification', models.TextField(blank=True)),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.anneescolaire')),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.bourseremise')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bourses', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Élève boursier',
                'verbose_name_plural': 'Élèves boursiers',
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
