# Generated by Django 4.2.11 on 2026-04-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_matiere_classe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'classe')},
        ),
    ]
