# Generated by Django 4.2.11 on 2026-04-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_add_mode_application_frais'),
        ('eleves', '0002_initial'),
        ('academics', '0004_alter_matiere_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne calculée automatiquement', max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, help_text='Rang dans la classe pour cette matière', null=True)),
                ('appreciation', models.TextField(blank=True, help_text='Appréciation du professeur')),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_notes', to='finances.cycleconfig')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_notes', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_notes', to='academics.matiere')),
            ],
            options={
                'verbose_name': 'Fiche de note',
                'verbose_name_plural': 'Fiches de notes',
                'ordering': ['eleve', 'matiere'],
                'unique_together': {('eleve', 'matiere', 'cycle')},
            },
        ),
    ]
