# Generated by Django 4.2.11 on 2026-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_add_mode_application_frais'),
        ('academics', '0005_add_fiche_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignement',
            options={'ordering': ['jour', 'heure_debut'], 'verbose_name': 'Enseignement', 'verbose_name_plural': 'Enseignements'},
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='heure_debut',
            field=models.TimeField(blank=True, help_text='Heure de début du cours', null=True),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='heure_fin',
            field=models.TimeField(blank=True, help_text='Heure de fin du cours', null=True),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='jour',
            field=models.CharField(blank=True, choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('professeur', 'classe', 'matiere', 'annee_scolaire', 'jour')},
        ),
    ]
