# Generated by Django 4.2.11 on 2026-04-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_add_mode_application_frais'),
        ('academics', '0006_add_horaire_enseignement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('professeur', 'classe', 'matiere', 'annee_scolaire', 'jour', 'heure_debut')},
        ),
    ]
