# Generated by Django 5.2.3 on 2026-04-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_add_titre_to_evaluation'),
        ('eleves', '0003_add_new_modules'),
        ('finances', '0010_add_new_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_salle', models.CharField(choices=[('classe', 'Salle de classe'), ('laboratoire', 'Laboratoire'), ('informatique', 'Salle informatique'), ('sport', 'Salle de sport'), ('bibliotheque', 'Bibliothèque'), ('autre', 'Autre')], default='classe', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=40)),
                ('etage', models.CharField(blank=True, help_text='Ex: RDC, 1er étage', max_length=20)),
                ('equipements', models.TextField(blank=True, help_text='Vidéoprojecteur, tableau interactif, etc.')),
                ('est_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ContrainteHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_contrainte', models.CharField(choices=[('indisponible', 'Indisponible'), ('preference', 'Préférence'), ('cours_physique', "Cours d'EPS"), ('reunion', 'Réunion'), ('autre', 'Autre')], max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('est_recurrent', models.BooleanField(default=True, help_text='Se répète chaque semaine')),
                ('date_fin', models.DateField(blank=True, help_text='Pour les contraintes temporaires', null=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='academics.professeur')),
            ],
            options={
                'verbose_name': 'Contrainte horaire',
                'verbose_name_plural': 'Contraintes horaires',
                'ordering': ['professeur', 'jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_examen', models.CharField(choices=[('trimestre1', '1er Trimestre'), ('trimestre2', '2ème Trimestre'), ('trimestre3', '3ème Trimestre'), ('semestre1', '1er Semestre'), ('semestre2', '2ème Semestre'), ('examen_blanc', 'Examen blanc'), ('examen_final', 'Examen final'), ('concours', 'Concours')], max_length=20)),
                ('date_examen', models.DateField()),
                ('duree_minutes', models.PositiveIntegerField(default=60, help_text='Durée en minutes')),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('est_publie', models.BooleanField(default=False, verbose_name='Résultats publiés')),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='finances.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academics.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academics.matiere')),
                ('surveillant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.salle')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='CoefficientMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='academics.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='academics.matiere')),
            ],
            options={
                'verbose_name': 'Coefficient',
                'verbose_name_plural': 'Coefficients',
                'unique_together': {('classe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appreciation', models.TextField(blank=True, help_text='Appréciation du correcteur')),
                ('est_corrige', models.BooleanField(default=False)),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='eleves.eleve')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='academics.examen')),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'unique_together': {('examen', 'eleve')},
            },
        ),
    ]
