# Generated by Django 5.2.3 on 2026-04-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_new_modules'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'filiere', 'annee_scolaire')},
        ),
    ]
