# Generated by Django 5.2.3 on 2026-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_classe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='domaine',
            field=models.CharField(blank=True, choices=[('Sciences', 'Sciences & Technologies'), ('SVT', 'Sciences de la Vie et de la Terre'), ('Economie', 'Sciences Économiques & Gestion'), ('Droit', 'Droit & Sciences Politiques'), ('Lettres', 'Lettres Arts & Sciences Humaines'), ('Education', "Sciences de l'Éducation"), ('Santé', 'Santé'), ('Communication', 'Communication & Journalisme')], max_length=50, verbose_name='Domaine (Université)'),
        ),
        migrations.AddField(
            model_name='classe',
            name='serie',
            field=models.CharField(blank=True, choices=[('A1', 'Série A1 - Lettres Langues Arts'), ('A2', 'Série A2 - Lettres Sciences Humaines'), ('C', 'Série C - Maths Sciences Physiques'), ('D', 'Série D - Sciences Vie Terre'), ('G1', 'Série G1 - Sciences économiques et sociales'), ('G2', 'Série G2 - Techniques quantitatives de gestion'), ('E', 'Série E - Maths Technologie'), ('F', 'Série F - Sciences Techniques Industrielles')], max_length=10, verbose_name='Série (Lycée)'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.CharField(blank=True, max_length=50, verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('CP1', 'Cours Préparatoire 1'), ('CP2', 'Cours Préparatoire 2'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('6e', 'Sixième'), ('5e', 'Cinquième'), ('4e', 'Quatrième'), ('3e', 'Troisième'), ('2nde', 'Seconde'), ('1re', 'Première'), ('Tle', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=10, verbose_name='Niveau'),
        ),
    ]
