# Generated by Django 5.2.3 on 2026-04-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_classe_domaine_classe_serie_alter_classe_filiere_and_more'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'filiere', 'serie', 'domaine', 'annee_scolaire')},
        ),
    ]
