# Generated by Django 5.2.3 on 2026-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_classe_unique_together'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'serie', 'domaine', 'annee_scolaire')},
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('Maternelle1', 'Maternelle 1'), ('Maternelle2', 'Maternelle 2'), ('CP1', 'Cours Préparatoire 1'), ('CP2', 'Cours Préparatoire 2'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('6e', 'Sixième'), ('5e', 'Cinquième'), ('4e', 'Quatrième'), ('3e', 'Troisième'), ('2nde', 'Seconde'), ('1re', 'Première'), ('Tle', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=15, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(choices=[('Maternelle 1', 'Maternelle 1'), ('Maternelle 2', 'Maternelle 2'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nde', '2nde'), ('1re', '1re'), ('Tle', 'Tle'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=50, verbose_name='Nom de la classe'),
        ),
        migrations.RemoveField(
            model_name='classe',
            name='filiere',
        ),
    ]
