# Generated by Django 5.2.3 on 2026-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_classe_unique_together_alter_classe_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='serie',
            field=models.CharField(blank=True, choices=[('TC', 'Tronc Commun'), ('A1', 'Série A1 - Lettres Langues Arts'), ('A2', 'Série A2 - Lettres Sciences Humaines'), ('C', 'Série C - Maths Sciences Physiques'), ('D', 'Série D - Sciences Vie Terre'), ('G1', 'Série G1 - Sciences économiques et sociales'), ('G2', 'Série G2 - Techniques quantitatives de gestion'), ('E', 'Série E - Maths Technologie'), ('F', 'Série F - Sciences Techniques Industrielles')], max_length=10, verbose_name='Série (Lycée)'),
        ),
    ]
