# Generated by Django 5.2.3 on 2026-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_classe_serie'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau', 'nom', 'subdivision'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classe',
            name='subdivision',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subdivision (ex: 1, 2, A, B...)'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'serie', 'domaine', 'subdivision', 'annee_scolaire')},
        ),
    ]
