# Generated by Django 5.2.3 on 2026-04-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_classe_options_alter_classe_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ClasseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1, verbose_name='Coefficient pour cette classe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.matiere')),
            ],
            options={
                'unique_together': {('classe', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(related_name='classes', through='academics.ClasseMatiere', through_fields=('classe', 'matiere'), to='academics.matiere'),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classe',
        ),
    ]
