# Generated by Django 5.2.3 on 2026-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_matiere_unique_together_classematiere_and_more'),
        ('eleves', '0008_add_note_periode_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='eleves',
            field=models.ManyToManyField(related_name='classes', through='eleves.Inscription', to='eleves.eleve'),
        ),
    ]
