# Generated by Django 5.2.3 on 2026-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_classe_eleves'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignement',
            options={'ordering': ['professeur', 'classe', 'matiere'], 'verbose_name': 'Enseignement', 'verbose_name_plural': 'Enseignements'},
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('professeur', 'classe', 'matiere', 'annee_scolaire')},
        ),
        migrations.AddField(
            model_name='enseignement',
            name='horaires',
            field=models.JSONField(blank=True, default=list, help_text="Liste des créneaux horaires [{'jour': 'lundi', 'heure_debut': '10:00', 'heure_fin': '12:00'}]"),
        ),
        migrations.RemoveField(
            model_name='enseignement',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='enseignement',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='enseignement',
            name='jour',
        ),
    ]
