# Generated by Django 5.2.3 on 2026-04-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_enseignement_options_and_more'),
        ('finances', '0010_add_new_modules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('professeur', 'classe', 'annee_scolaire')},
        ),
    ]
