# Generated by Django 5.2.3 on 2026-04-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_alter_enseignement_unique_together'),
        ('authentification', '0016_alter_demandeapprobation_type_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraintehoraire',
            name='demande_approuver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraintes_approuvees', to='authentification.demandeapprobation'),
        ),
        migrations.AddField(
            model_name='contraintehoraire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='approuve', max_length=20),
        ),
        migrations.AlterField(
            model_name='contraintehoraire',
            name='type_contrainte',
            field=models.CharField(choices=[('conge', 'Congé'), ('maladie', 'Maladie'), ('permission', 'Permission'), ('formation', 'Formation'), ('absence', 'Absence'), ('autre', 'Autre')], max_length=20),
        ),
    ]
