# Generated by Django 5.2.3 on 2026-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_add_periode_to_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='note_conduite_base',
            field=models.PositiveIntegerField(default=20, help_text='Note de conduite de base sur 20 pour cette classe'),
        ),
    ]
