# Generated by Django 5.2.3 on 2026-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_add_note_conduite_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
