from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-recovery/', views.PasswordRecoveryView.as_view(), name='password_recovery'),
    path('password-recovery/verify/', views.PasswordRecoveryVerifyView.as_view(), name='password_recovery_verify'),
    path('password-recovery/reset/', views.PasswordRecoveryResetView.as_view(), name='password_recovery_reset'),
    path('profile/', views.profile, name='profile'),
    path('users/', views.user_list, name='user_list'),
    path('users/ajouter/', views.user_create, name='user_create'),
    path('users/<int:pk>/modifier/', views.user_update, name='user_update'),
    path('users/<int:pk>/supprimer/', views.user_delete, name='user_delete'),
    path('users/<int:pk>/approuver/', views.user_approve, name='user_approve'),
    path('users/<int:pk>/toggle-active/', views.user_toggle_active, name='user_toggle_active'),
    path('users/<int:pk>/permissions/', views.user_permissions_detail, name='user_permissions_detail'),
    path('users/<int:pk>/reset-password/', views.user_reset_password, name='user_reset_password'),
    path('users/<int:user_pk>/permission/<str:module_code>/toggle/', views.user_permission_toggle, name='user_permission_toggle'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/mark-all-read/', views.notification_mark_all_read, name='notification_mark_all_read'),
    path('notifications/<int:pk>/', views.notification_detail, name='notification_detail'),
    path('messages/', views.message_list, name='message_list'),
    path('messages/<int:conversation_id>/', views.message_list, name='message_conversation'),
    path('chat/', views.message_list, name='chat_inbox'),
    path('messages/nouveau/', views.message_create, name='message_create'),
    path('messages/marquer-tout-lu/', views.message_mark_all_read, name='message_mark_all_read'),
    path('messages/detail/<int:pk>/', views.message_detail, name='message_detail'),
    path('chat/demarrer/<int:user_id>/', views.conversation_start, name='conversation_start'),
    path('chat/<int:conversation_id>/envoyer/', views.conversation_send, name='conversation_send'),
    path('chat/<int:conversation_id>/supprimer/', views.conversation_delete, name='conversation_delete'),
    path('messages/<int:pk>/supprimer/', views.message_delete, name='message_delete'),
    path('api/updates/', views.api_updates, name='api_updates'),
    path('permissions-utilisateur/', views.permissions_utilisateur, name='permissions_utilisateur'),
    path('permissions-utilisateur/nouvelle/', views.permission_utilisateur_create, name='permission_utilisateur_create'),
    path('permissions-utilisateur/<int:pk>/modifier/', views.permission_utilisateur_edit, name='permission_utilisateur_edit'),
    path('permissions-utilisateur/<int:pk>/supprimer/', views.permission_utilisateur_delete, name='permission_utilisateur_delete'),
    path('demandes/', views.demandes_list, name='demandes_list'),
    path('demandes/<int:pk>/', views.demande_detail, name='demande_detail'),
    path('demandes/<int:pk>/approuver/', views.demande_approuver, name='demande_approuver'),
    path('demandes/<int:pk>/rejeter/', views.demande_rejeter, name='demande_rejeter'),
    path('journal-audit/', views.audit_log, name='audit_log'),
]
